import { execSync } from 'node:child_process'
import {
  copyFileSync,
  mkdirSync,
  writeFileSync,
  existsSync,
  readdirSync,
  statSync,
  rmSync,
} from 'node:fs'
import { join, resolve, dirname } from 'node:path'
import { homedir, platform } from 'node:os'
import { fileURLToPath } from 'node:url'

const HOST_NAME = 'com.webcli.dom'
const MANIFEST_FILENAME = `${HOST_NAME}.json`
const WEBCLI_HOME = join(homedir(), '.webcli-dom')
const EXTENSION_DIR = join(WEBCLI_HOME, 'extension')

export function getNativeHostPath(): string {
  const home = homedir()

  switch (process.platform) {
    case 'darwin':
      return join(home, 'Library', 'Application Support', 'Google', 'Chrome', 'NativeMessagingHosts', MANIFEST_FILENAME)
    case 'linux':
      return join(home, '.config', 'google-chrome', 'NativeMessagingHosts', MANIFEST_FILENAME)
    default:
      throw new Error(`Unsupported platform: ${process.platform}`)
  }
}

export function getNativeHostManifest(binaryPath: string, extensionId: string) {
  return {
    name: HOST_NAME,
    description: 'webcli-dom MCP server native messaging host',
    path: binaryPath,
    type: 'stdio' as const,
    allowed_origins: [`chrome-extension://${extensionId}/`],
  }
}

export function installNativeHost(binaryPath: string, extensionId: string): string {
  const manifestPath = getNativeHostPath()
  const manifest = getNativeHostManifest(binaryPath, extensionId)

  mkdirSync(dirname(manifestPath), { recursive: true })
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), 'utf-8')

  return manifestPath
}

// --- Auto-install ---

function findProjectRoot(): string {
  const thisDir = typeof __dirname !== 'undefined'
    ? __dirname
    : dirname(fileURLToPath(import.meta.url))
  let dir = resolve(thisDir)
  while (dir !== '/') {
    if (existsSync(join(dir, 'pnpm-workspace.yaml'))) return dir
    dir = resolve(dir, '..')
  }
  throw new Error('Could not find project root (no pnpm-workspace.yaml found)')
}

function copyDir(src: string, dest: string): void {
  mkdirSync(dest, { recursive: true })
  for (const entry of readdirSync(src)) {
    const srcPath = join(src, entry)
    const destPath = join(dest, entry)
    if (statSync(srcPath).isDirectory()) {
      copyDir(srcPath, destPath)
    } else {
      copyFileSync(srcPath, destPath)
    }
  }
}

export async function runInstall(options?: { extensionId?: string }): Promise<void> {
  console.log('webcli-dom: Installing...\n')

  // 1. Create ~/.webcli-dom/ directory
  mkdirSync(WEBCLI_HOME, { recursive: true })

  // 2. Find project root and build the extension
  const projectRoot = findProjectRoot()
  const extensionPkg = join(projectRoot, 'packages/extension')

  console.log('1. Building extension...')
  execSync('pnpm run build', { cwd: extensionPkg, stdio: 'inherit' })

  // 3. Copy extension to stable location (~/.webcli-dom/extension/)
  console.log('2. Installing extension to ~/.webcli-dom/extension/...')
  // Clean previous installation
  if (existsSync(EXTENSION_DIR)) {
    rmSync(EXTENSION_DIR, { recursive: true })
  }
  mkdirSync(EXTENSION_DIR, { recursive: true })

  // Copy dist/ directory (contains built JS)
  const distDir = join(extensionPkg, 'dist')
  if (existsSync(distDir)) {
    copyDir(distDir, join(EXTENSION_DIR, 'dist'))
  }

  // Copy manifest.json
  copyFileSync(join(extensionPkg, 'manifest.json'), join(EXTENSION_DIR, 'manifest.json'))

  // Copy popup.html if it exists (manifest references src/popup/popup.html)
  const popupHtml = join(extensionPkg, 'src/popup/popup.html')
  if (existsSync(popupHtml)) {
    mkdirSync(join(EXTENSION_DIR, 'src/popup'), { recursive: true })
    copyFileSync(popupHtml, join(EXTENSION_DIR, 'src/popup/popup.html'))
  }

  // 4. Create wrapper shell script (like Claude Code's pattern)
  console.log('3. Creating native host wrapper...')
  const wrapperPath = join(WEBCLI_HOME, 'native-host')
  const selfPath = resolve(process.argv[1])
  writeFileSync(
    wrapperPath,
    [
      '#!/bin/sh',
      '# webcli-dom native messaging host',
      '# Generated by webcli-mcp install - do not edit manually',
      `exec "${process.execPath}" "${selfPath}" --native-host`,
      '',
    ].join('\n'),
    { mode: 0o755 },
  )

  // 5. Install Native Messaging Host config
  console.log('4. Installing native messaging host config...')
  const extensionId = options?.extensionId || 'PLACEHOLDER_EXTENSION_ID'
  const hostPath = installNativeHost(wrapperPath, extensionId)
  console.log(`   -> ${hostPath}`)

  if (!options?.extensionId) {
    console.log('   (Using placeholder extension ID - re-run with --extension-id=<id> to finalize)')
  }

  // 6. Open Chrome with the unpacked extension on macOS
  console.log('\n5. Loading extension in Chrome...')
  console.log('   Extension installed to:', EXTENSION_DIR)

  if (platform() === 'darwin') {
    try {
      execSync(`open -a "Google Chrome" --args --load-extension="${EXTENSION_DIR}"`)
      console.log('   -> Chrome opened with extension loaded')
    } catch {
      console.log('   -> Could not auto-open Chrome. Please load manually:')
      console.log(`     chrome://extensions -> Load unpacked -> ${EXTENSION_DIR}`)
    }
  } else {
    console.log('   Load the extension manually:')
    console.log(`   chrome://extensions -> Developer mode ON -> Load unpacked -> ${EXTENSION_DIR}`)
  }

  // 7. Summary
  console.log('\nInstallation complete!')
  if (!options?.extensionId) {
    console.log('\nNext steps:')
    console.log('  1. Find the extension ID in chrome://extensions')
    console.log('  2. Re-run: webcli-mcp install --extension-id=<your-extension-id>')
    console.log('     to finalize the native messaging host configuration.')
  } else {
    console.log(`\nNative messaging host configured for extension: ${options.extensionId}`)
  }
}
