import type { Task, Member } from './types'

export const SEED_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Design landing page mockups',
    description: 'Create high-fidelity mockups for the new landing page including mobile and desktop views.',
    status: 'done',
    priority: 'high',
    assignee: 'Alice Chen',
    order: 0,
    createdAt: '2026-03-01T10:00:00Z',
    dueDate: '2026-03-10',
    tags: ['design', 'feature'],
    estimatedHours: 16,
  },
  {
    id: 'task-2',
    title: 'Implement authentication flow',
    description: 'Build login, registration, and password reset flows using OAuth2 and JWT tokens.',
    status: 'in-progress',
    priority: 'high',
    assignee: 'Bob Kim',
    order: 0,
    createdAt: '2026-03-05T09:00:00Z',
    dueDate: '2026-03-20',
    tags: ['feature', 'urgent'],
    estimatedHours: 24,
  },
  {
    id: 'task-3',
    title: 'Set up CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing, linting, and deployment to staging.',
    status: 'in-review',
    priority: 'medium',
    assignee: 'Charlie Park',
    order: 0,
    createdAt: '2026-03-08T14:00:00Z',
    dueDate: '2026-03-25',
    tags: ['enhancement'],
    estimatedHours: 8,
  },
  {
    id: 'task-4',
    title: 'Write API documentation',
    description: 'Document all REST API endpoints with request/response examples using OpenAPI spec.',
    status: 'todo',
    priority: 'medium',
    assignee: 'Diana Lee',
    order: 0,
    createdAt: '2026-03-10T11:00:00Z',
    dueDate: '2026-03-30',
    tags: ['documentation'],
    estimatedHours: 12,
  },
  {
    id: 'task-5',
    title: 'Database schema optimization',
    description: 'Review and optimize database queries, add missing indexes for performance improvement.',
    status: 'todo',
    priority: 'low',
    assignee: 'Bob Kim',
    order: 1,
    createdAt: '2026-03-12T16:00:00Z',
  },
  {
    id: 'task-6',
    title: 'User acceptance testing',
    description: 'Coordinate UAT sessions with stakeholders and gather feedback for the beta release.',
    status: 'todo',
    priority: 'high',
    assignee: 'Eve Wang',
    order: 2,
    createdAt: '2026-03-14T08:00:00Z',
  },
  {
    id: 'task-7',
    title: 'Mobile responsive fixes',
    description: 'Fix layout issues on tablet and mobile viewports for the dashboard pages.',
    status: 'in-progress',
    priority: 'medium',
    assignee: 'Alice Chen',
    order: 1,
    createdAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'task-8',
    title: 'Performance audit',
    description: 'Run Lighthouse audits and fix critical performance bottlenecks to achieve 90+ score.',
    status: 'in-review',
    priority: 'low',
    assignee: 'Frank Zhang',
    order: 1,
    createdAt: '2026-03-16T13:00:00Z',
  },
]

/** Generate initials-based avatar placeholder string from a name */
export function getAvatarInitials(name: string): string {
  return name
    .split(' ')
    .map((part) => part[0])
    .join('')
    .toUpperCase()
    .slice(0, 2)
}

export const SEED_MEMBERS: Member[] = [
  {
    id: 'member-1',
    name: 'Alice Chen',
    email: 'alice@example.com',
    role: 'designer',
    status: 'active',
    joinedAt: '2025-06-15',
    avatar: 'AC',
  },
  {
    id: 'member-2',
    name: 'Bob Kim',
    email: 'bob@example.com',
    role: 'developer',
    status: 'active',
    joinedAt: '2025-07-01',
    avatar: 'BK',
  },
  {
    id: 'member-3',
    name: 'Charlie Park',
    email: 'charlie@example.com',
    role: 'developer',
    status: 'active',
    joinedAt: '2025-08-20',
    avatar: 'CP',
  },
  {
    id: 'member-4',
    name: 'Diana Lee',
    email: 'diana@example.com',
    role: 'qa',
    status: 'active',
    joinedAt: '2025-09-10',
    avatar: 'DL',
  },
  {
    id: 'member-5',
    name: 'Eve Wang',
    email: 'eve@example.com',
    role: 'admin',
    status: 'active',
    joinedAt: '2025-05-01',
    avatar: 'EW',
  },
  {
    id: 'member-6',
    name: 'Frank Zhang',
    email: 'frank@example.com',
    role: 'developer',
    status: 'inactive',
    joinedAt: '2025-10-15',
    avatar: 'FZ',
  },
  {
    id: 'member-7',
    name: 'Grace Liu',
    email: 'grace@example.com',
    role: 'designer',
    status: 'active',
    joinedAt: '2025-11-01',
    avatar: 'GL',
  },
  {
    id: 'member-8',
    name: 'Henry Wu',
    email: 'henry@example.com',
    role: 'qa',
    status: 'inactive',
    joinedAt: '2025-12-01',
    avatar: 'HW',
  },
  {
    id: 'member-9',
    name: 'Iris Tanaka',
    email: 'iris@example.com',
    role: 'developer',
    status: 'active',
    joinedAt: '2025-07-20',
    avatar: 'IT',
  },
  {
    id: 'member-10',
    name: 'Jack Morrison',
    email: 'jack@example.com',
    role: 'developer',
    status: 'active',
    joinedAt: '2025-08-05',
    avatar: 'JM',
  },
  {
    id: 'member-11',
    name: 'Karen Singh',
    email: 'karen@example.com',
    role: 'qa',
    status: 'active',
    joinedAt: '2025-09-25',
    avatar: 'KS',
  },
  {
    id: 'member-12',
    name: 'Leo Martinez',
    email: 'leo@example.com',
    role: 'designer',
    status: 'active',
    joinedAt: '2025-10-01',
    avatar: 'LM',
  },
  {
    id: 'member-13',
    name: 'Mia Johnson',
    email: 'mia@example.com',
    role: 'admin',
    status: 'active',
    joinedAt: '2025-04-15',
    avatar: 'MJ',
  },
  {
    id: 'member-14',
    name: 'Nathan Patel',
    email: 'nathan@example.com',
    role: 'developer',
    status: 'active',
    joinedAt: '2025-11-10',
    avatar: 'NP',
  },
  {
    id: 'member-15',
    name: 'Olivia Brown',
    email: 'olivia@example.com',
    role: 'qa',
    status: 'inactive',
    joinedAt: '2025-06-01',
    avatar: 'OB',
  },
  {
    id: 'member-16',
    name: 'Peter Nguyen',
    email: 'peter@example.com',
    role: 'developer',
    status: 'active',
    joinedAt: '2025-12-15',
    avatar: 'PN',
  },
  {
    id: 'member-17',
    name: 'Quinn Riley',
    email: 'quinn@example.com',
    role: 'designer',
    status: 'active',
    joinedAt: '2026-01-05',
    avatar: 'QR',
  },
  {
    id: 'member-18',
    name: 'Rachel Torres',
    email: 'rachel@example.com',
    role: 'developer',
    status: 'inactive',
    joinedAt: '2025-08-15',
    avatar: 'RT',
  },
  {
    id: 'member-19',
    name: 'Sam O\'Brien',
    email: 'sam@example.com',
    role: 'qa',
    status: 'active',
    joinedAt: '2026-01-20',
    avatar: 'SO',
  },
  {
    id: 'member-20',
    name: 'Tina Yamamoto',
    email: 'tina@example.com',
    role: 'admin',
    status: 'active',
    joinedAt: '2025-05-20',
    avatar: 'TY',
  },
  {
    id: 'member-21',
    name: 'Uma Krishnan',
    email: 'uma@example.com',
    role: 'developer',
    status: 'active',
    joinedAt: '2026-02-01',
    avatar: 'UK',
  },
  {
    id: 'member-22',
    name: 'Victor Sousa',
    email: 'victor@example.com',
    role: 'designer',
    status: 'inactive',
    joinedAt: '2025-09-05',
    avatar: 'VS',
  },
]
